# Generated by Django 5.0.4 on 2024-06-12 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_description',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_image',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_name',
        ),
        migrations.AddField(
            model_name='receipe',
            name='image',
            field=models.ImageField(default='', upload_to='receipe'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipdes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
